### ISSUE TITLE
Unable to pass 'user agreement' on main page

### ISSUE THREAD

**Issue by adeptzero** [jackyzy823/rajiko#2]
Started having this issue today where I cannot get past the front page user agreement. Clicking on the "I agree" button is not closing the pop-up or doing anything.

![image](https://user-images.githubusercontent.com/81189860/112049065-84067a80-8b25-11eb-83b0-8906cdab083f.png)

![image](https://user-images.githubusercontent.com/81189860/112051572-7999b000-8b28-11eb-9f96-556a065bfd00.png)

Thanks!

**Comment by wildthingsan** [comment]
Users within Japan are no longer able to change regions.

If users were coming from non Japan IPs able to change the region and access, the above popup "not to be used in any other country" appears in both cases.

Strange thing I noticed, after I had access the site from outside IP and sucessfuly set a different region, my current session I can flip between the regions fine from Japan IP now.

**Comment by jackyzy823** [comment]
There're two dialogs  1. for Private Policy 2. for users overseas. 

For non-japan users  two dialogs will be displayed at same time which makes "I agree" button not work.

I'll try to bypass this.

**Comment by jackyzy823** [comment]
I uploaded v0.2.7 to Chrome Web Store. Waiting for Chrome Web Store's review.
Or you could load extension from source code.

**Comment by wildthingsan** [comment]
Thanks looking good, no issues within Japan on switching regions.

**Comment by cheyq99** [comment]
v0.2.7 is working well, thanks a lot.

**Comment by fallingleaflun** [comment]
Same problem again, I think radiko is supervising this project

**Comment by wildthingsan** [comment]
update, seems if you attempt to use in Japan it kicks you out of website, workaround similar as before seems if I vpn from Japan I can still use the plugin and switch region.

**Comment by jackyzy823** [comment]
@wildthingsan  sorry for the inconvenience. v0.2.7.1 is only tested in `firefox` . And `chrome` treats history differently with `firefox`. i made a revert release v0.2.7.2.

**Comment by jackyzy823** [comment]
Why i do the change?

Because i want if user enter with link `https://radiko.jp/#!/live/TBS` and the can bypass the `#!/out` and still in the same page `https://radiko.jp/#!/live/TBS` instead of going to  the homepage `https://radiko.jp/`

In firefox `history.back()` works as a charm.

In chrome see https://stackoverflow.com/questions/58128939/changing-window-location-hash-creates-entry-in-history-but-doesnt-affect-chrome
and 
https://stackoverflow.com/questions/58128939/changing-window-location-hash-creates-entry-in-history-but-doesnt-affect-chrome

And 
https://chromium-review.googlesource.com/c/chromium/src/+/1344199

**Comment by wildthingsan** [comment]
v0.2.7.2 working well in Japan in Chrome thanks, also tested firefox plugin but had to bypass the user agreement once but it was ok.

**Comment by adeptzero** [comment]
Appreciate the quick fixes as always. Confirming 2.7.2 working well outside Japan also.

**Comment by jackyzy823** [comment]
hello everyone. I make a update to v0.2.8 which makes history work.

Can anyone help test this version on chrome from zip package  https://github.com/jackyzy823/rajiko/archive/refs/tags/v0.2.8.zip before i upload this to  chrome web store (no more bad releases :disappointed: ), thanks.

**Comment by andykamezou** [comment]
I was about to reply that you made a typo in 0.2.7.2, which basically does not fix much. And it makes me wonder if @wildthingsan's issue with **switching region** was caused by something else and not related to this extension. 🤔

A quick test on 0.2.8 seems fine on Brave, ~~even fixed the issue with share url~~
As for Edge, it works well for this issue. Will leave some other feedback in #3

**Comment by wildthingsan** [comment]
Hi, I tested the v0.2.8.zip from Japan IP and its working well, I was able to change different regions and tested downloading as well.
So I think functinoally it working fine again. (I also check plugin after an exit and restart of Chrome browser, there was odd issues before when it was kicking me out of the website with the earlier versions)

**Comment by wildthingsan** [comment]
@adeptzero We should close this ticket as it has been fixed.

**Comment by adeptzero** [comment]
Closed thanks.
